"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 10
add_newline = true

palette = 'catppuccin_frappe'

format = """
[╭─](bold green_bright)\
$nix_shell\
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$env_var\
$custom\
$cmd_duration\
$jobs\
$os\
$container\
$netns\
$shell\
$fill\
$line_break\
[╰─](bold green_bright)\
$character\
$status\
$sudo"""

[fill]
symbol = ' '

[direnv]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true



# left
# ------------------------------------------

[character] 
success_symbol = '[](bold green_bright)'
error_symbol = '[](bold red_bright)'

[cmd_duration]
format = ' [ $duration](bold blue1) '
show_milliseconds = true

[directory]
truncation_symbol = ''
read_only = " "
style = 'bold cyan_bright'

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold magenta_bright)'

[git_status]
style = 'bold magenta_bright'

[nix_shell]
format = '[ ](bold white0_reduce_blue)'

[status]
disabled = false
symbol = '✘ '
format = '[$symbol](bold red_base)'

[sudo]
disabled = false
format = '[ sudo: ](bold red_bright)'

# right
# ------------------------------------------

[docker_context]
format = ' [ $context](bold blue1) '

[dotnet]
format = '[ ($version )](bold blue0) '
version_format = 'v${major}.${minor}'

[golang]
format = '[ $version](bold cyan_bright) '
version_format = 'v${major}.${minor}'

[gradle]
format = '[ ($version)](bold green_bright) '
version_format = 'v${major}.${minor}'

[java]
format = '[ ${version}](bold red_bright) '
version_format = 'v${major}.${minor}'

[lua]
format = '[ $version](bold blue1) '
version_format = 'v${major}.${minor}'

[nodejs]
format = ' [ ($version)](bold green_bright) '
version_format = 'v${major}.${minor}'

[pulumi]
format = ' [pulumi ($username@)$stack](bold magenta_bright) '
version_format = 'v${major}.${minor}'

[python]
format = ' [ ${pyenv_prefix}(${version} )(\($virtualenv\) )](bold green_bright) '
version_format = 'v${major}.${minor}'

[rust]
format = ' [󱘗 $version](bold red_bright) '
version_format = 'v${major}.${minor}'

[terraform]
format = ' [󰆩 $workspace](bold magenta_bright) '
version_format = 'v${major}.${minor}'

# Palette
# ------------------------------------------
[palettes.catppuccin_frappe]
white0_reduce_blue = '#c6d0f5'
red_base = '#e78284'
red_bright = '#ea999c'
green_bright = '#a6d189'
cyan_bright = '#99d1db'
blue0 = '#8caaee'
blue1 = '#85c1dc'
magenta_bright = '#ca9ee6'
